// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/processor/profilingprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/processor/profilingprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                         metric.Meter
	mu                            sync.Mutex
	registrations                 []metric.Registration
	ProcessorProfilingErrorCount  metric.Int64Counter
	ProcessorProfilingPayloadSize metric.Int64Histogram
	ProcessorProfilingSuccessRate metric.Float64Gauge
	ProcessorProfilingThroughput  metric.Float64Gauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorProfilingErrorCount, err = builder.meter.Int64Counter(
		"otelcol_processor_profiling_error_count",
		metric.WithDescription("Total number of errors in the profiled pipeline segment by type [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorProfilingPayloadSize, err = builder.meter.Int64Histogram(
		"otelcol_processor_profiling_payload_size",
		metric.WithDescription("Distribution of payload sizes in bytes [Development]"),
		metric.WithUnit("Bytes"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorProfilingSuccessRate, err = builder.meter.Float64Gauge(
		"otelcol_processor_profiling_success_rate",
		metric.WithDescription("Success rate of the profiled pipeline segment [Development]"),
		metric.WithUnit("%"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorProfilingThroughput, err = builder.meter.Float64Gauge(
		"otelcol_processor_profiling_throughput",
		metric.WithDescription("Throughput of the profiled pipeline segment in items per second [Development]"),
		metric.WithUnit("kB/s"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
